---
name: cin7_configs
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverStripers\Cin7\Extension\Config

SilverShop\Page\Product:
  extensions:
    - SilverStripers\Cin7\Extension\ProductExtension

SilverShop\Model\Variation\Variation:
  extensions:
    - SilverStripers\Cin7\Extension\VariationExtension

SilverStripe\Assets\File:
  extensions:
    - SilverStripers\Cin7\Extension\FileExtension

SilverShop\Model\Variation\AttributeType:
  extensions:
    - SilverStripers\Cin7\Extension\AttributeTypeExtension
