---
name: cin7_configs
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverStripers\Cin7\Extension\Config

SilverShop\Page\Product:
  extensions:
    - SilverStripers\Cin7\Extension\ProductExtension

SilverShop\Model\OrderItem:
  extensions:
    - SilverStripers\Cin7\Extension\OrderItemExtension

SilverShop\Model\Order:
  extensions:
    - SilverStripers\Cin7\Extension\OrderExtension

SilverStripe\Security\Member:
  extensions:
    - SilverStripers\Cin7\Extension\MemberExtension

SilverStripe\ORM\FieldType\DBDatetime:
  extensions:
    - SilverStripers\Cin7\Extension\DatetimeExtension

SilverShop\Model\Variation\Variation:
  extensions:
    - SilverStripers\Cin7\Extension\VariationExtension

SilverStripe\Assets\File:
  extensions:
    - SilverStripers\Cin7\Extension\FileExtension

SilverShop\Model\Variation\AttributeType:
  extensions:
    - SilverStripers\Cin7\Extension\AttributeTypeExtension

SilverShop\Admin\ProductCatalogAdmin:
  extensions:
    - SilverStripers\Cin7\Extension\ProductCatalogAdminExtension
